openapi: 3.0.1
info:
  title: '@jupiterone/graph-snyk'
  description: A JupiterOne integration for Snyk.
  x-cortex-git:
    github:
      repository: JupiterOne/graph-snyk
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-snyk'
